/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class JFrameUsers extends javax.swing.JFrame {

    /**
     * Creates new form JFrameUsers
     */
    public JFrameUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        AgendaPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AgendaPU").createEntityManager();
        usuarioQuery = java.beans.Beans.isDesignTime() ? null : AgendaPUEntityManager.createQuery("SELECT u FROM Usuario u");
        usuarioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(usuarioQuery.getResultList());
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jLabelNome = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelConSenha = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jPasswordFieldConSenha = new javax.swing.JPasswordField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonInserir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonVerTarefas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuários");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usuarioList, jTableUsers);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${senha}"));
        columnBinding.setColumnName("Senha");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTableUsers);

        jLabelNome.setText("Nome");

        jLabelId.setText("Id");

        jLabelSenha.setText("Senha");

        jLabelConSenha.setText("Confirma Senha");

        jTextFieldId.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableUsers, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.id}"), jTextFieldId, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableUsers, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), jTextFieldNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableUsers, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.senha}"), jPasswordFieldSenha, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPasswordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaKeyPressed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonVerTarefas.setText("Ver Tarefas");
        jButtonVerTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerTarefasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNome)
                                    .addComponent(jLabelId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelConSenha)
                                    .addComponent(jLabelSenha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordFieldSenha)
                                    .addComponent(jPasswordFieldConSenha)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVerTarefas)
                                .addGap(6, 6, 6)))
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordFieldConSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelConSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerTarefas)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonInserir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
        this.jButtonInserir.setEnabled(false);
        this.jButtonExcluir.setEnabled(false);
        this.jButtonCancelar.setEnabled(true);
        this.jButtonSalvar.setEnabled(true);
        this.jButtonVerTarefas.setEnabled(this.jTableUsers.getRowCount() != 0);
 
        if (this.estado == Estado.CONSULTANDO) {
            if (this.jTableUsers.getRowCount() != 0) {
                this.estado = Estado.EDITANDO;
            } else {
                this.jButtonInserirActionPerformed(null);
            }
        }
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        // TODO add your handling code here:
         // Cria o objeto e insere na lista
        Usuario usuario = new Usuario();
        this.usuarioList.add(usuario);
 
        // Seleciona objeto inserido na lista e estabelece foco
        this.jTableUsers.setRowSelectionInterval(this.jTableUsers.getRowCount() - 1, this.jTableUsers.getRowCount() - 1);
        this.jTextFieldNome.requestFocus();
 
        //Configura botões
        this.jButtonInserir.setEnabled(false);
        this.jButtonExcluir.setEnabled(false);
        this.jButtonCancelar.setEnabled(true);
        this.jButtonSalvar.setEnabled(true);
        this.jButtonVerTarefas.setEnabled(false);
 
        this.estado = Estado.INSERINDO;
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        try {
            if (this.jPasswordFieldSenha.getText().equals(this.jPasswordFieldConSenha.getText())) {
                // Cria e configura o objeto
                Usuario usuario = new Usuario();
 
 
                if (this.estado == Estado.INSERINDO) {
 
                    // Atualiza o objeto
                    usuario.setNome(this.jTextFieldNome.getText());
                    usuario.setSenha(this.jPasswordFieldSenha.getText());
 
                    if (usuario.armazenado()) { // Se armazenado objeto no BD
 
                        // Retira o objeto da lista e o adiciona com o id
                        this.usuarioList.remove(this.jTableUsers.getSelectedRow());
                        this.usuarioList.add(usuario);
 
                        // Seleciona o último da lista
                        this.jTableUsers.setRowSelectionInterval(this.jTableUsers.getRowCount() - 1, this.jTableUsers.getRowCount() - 1);
                        this.jButtonInserir.setEnabled(true);
                        this.jButtonExcluir.setEnabled(this.jTableUsers.getRowCount() != 0);
                        this.jButtonCancelar.setEnabled(false);
                        this.jButtonSalvar.setEnabled(false);
                        this.jButtonVerTarefas.setEnabled(this.jTableUsers.getRowCount() != 0);
 
                        this.estado = Estado.CONSULTANDO;
                    }
                } else {
                    // Encontra e carrega o objeto de atualização
                    if (usuario.encontradoId(Long.valueOf(this.jTextFieldId.getText()))) {
 
                        // Atualiza o objeto
                        usuario.setNome(this.jTextFieldNome.getText());
                        usuario.setSenha(this.jPasswordFieldSenha.getText());
 
                        if (usuario.atualizado()) { // Se atualizado objeto no BD
 
                            // Seleciona o último da lista
                            this.jButtonInserir.setEnabled(true);
                            this.jButtonExcluir.setEnabled(this.jTableUsers.getRowCount() != 0);
                            this.jButtonCancelar.setEnabled(false);
                            this.jButtonSalvar.setEnabled(false);
                            this.jButtonVerTarefas.setEnabled(this.jTableUsers.getRowCount() != 0);
 
                            this.estado = Estado.CONSULTANDO;
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Confirmação de senha não coincidente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
         try {
            if (this.estado == Estado.INSERINDO) {
                this.usuarioList.remove(this.jTableUsers.getSelectedRow()); // Remove objeto inserido na lista
                if (this.jTableUsers.getRowCount() > 0) { // Se houver objetos na lista
                    // Seleciona o último da lista
                    this.jTableUsers.setRowSelectionInterval(this.jTableUsers.getRowCount() - 1, this.jTableUsers.getRowCount() - 1);
                }
            } else {
                Usuario usuario = new Usuario();
                if (usuario.encontradoId(Long.valueOf(this.jTextFieldId.getText()))) {
                    this.jTextFieldNome.setText(usuario.getNome());
                    this.jPasswordFieldSenha.setText(usuario.getSenha());
                }
 
            }
 
            //Configura botões
            this.jButtonInserir.setEnabled(true);
            this.jButtonExcluir.setEnabled(this.jTableUsers.getRowCount() != 0);
            this.jButtonCancelar.setEnabled(false);
            this.jButtonSalvar.setEnabled(false);
            this.jButtonVerTarefas.setEnabled(this.jTableUsers.getRowCount() != 0);
            this.estado = Estado.CONSULTANDO;
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Confirma a exclusão deste registro?") == JOptionPane.OK_OPTION) {
            try {
                Usuario usuario = new Usuario(); // Cria o objeto
                usuario.setId(Long.valueOf(this.jTextFieldId.getText())); // Configura o id de exclusão 
                if (usuario.desarmazenado()) { // Exclui o objeto do BD
                    int linhaSelecionada = this.jTableUsers.getSelectedRow(); // Marca linha selecionada da tabela
                    this.usuarioList.remove(this.jTableUsers.getSelectedRow()); // Remove objeto da lista
                    if (this.jTableUsers.getRowCount() > 0) { // Se houver linhas na tabela
                        if (linhaSelecionada > 0) {
                            linhaSelecionada--;
                        }
                        this.jTableUsers.setRowSelectionInterval(linhaSelecionada, linhaSelecionada); // Seleciona linha marcada
                    }
 
                    //Configura botões
                    this.jButtonInserir.setEnabled(true);
                    this.jButtonExcluir.setEnabled(this.jTableUsers.getRowCount() != 0);
                    this.jButtonCancelar.setEnabled(false);
                    this.jButtonSalvar.setEnabled(false);
                    this.jButtonVerTarefas.setEnabled(this.jTableUsers.getRowCount() != 0);
 
                    this.estado = Estado.CONSULTANDO;
 
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (this.jTableUsers.getRowCount() > 0) { // Se houver linhas na lista
            this.jTableUsers.setRowSelectionInterval(0, 0); // Seleciona linha 0
        }
 
        // Configura botões 
        this.jButtonInserir.setEnabled(true);
        this.jButtonExcluir.setEnabled(this.jTableUsers.getRowCount() != 0);
        this.jButtonCancelar.setEnabled(false);
        this.jButtonSalvar.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonVerTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerTarefasActionPerformed
        // TODO add your handling code here:
        // Busca usuário e passa-o para janela de tarefas
        Usuario usuario = new Usuario(); 
        usuario.encontradoId(Long.valueOf(this.jTextFieldId.getText()));
        
        JFrameTarefas jFrameTarefas = new JFrameTarefas(usuario);
        jFrameTarefas.setLocationRelativeTo(null); // Janela no centro
        
        jFrameTarefas.setVisible(true);
    }//GEN-LAST:event_jButtonVerTarefasActionPerformed

    private void jPasswordFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaKeyPressed
        // TODO add your handling code here:
        Usuario usuario = new Usuario(); 
        usuario.encontradoId(Long.valueOf(this.jTextFieldId.getText()));
        
        JFrameTarefas jFrameTarefas = new JFrameTarefas(usuario);
        jFrameTarefas.setLocationRelativeTo(null); // Janela no centro
        
        jFrameTarefas.setVisible(true);
    }//GEN-LAST:event_jPasswordFieldSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    
    private enum Estado {
        INSERINDO,
        EDITANDO,
        CONSULTANDO
    }
 
    private Estado estado = Estado.CONSULTANDO;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AgendaPUEntityManager;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVerTarefas;
    private javax.swing.JLabel jLabelConSenha;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPasswordField jPasswordFieldConSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNome;
    private java.util.List<Controller.Usuario> usuarioList;
    private javax.persistence.Query usuarioQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
